stages:
  - test
  - deploy
  - postdeploy

image: edbizarro/gitlab-ci-pipeline-php:7.3

variables:
  SURF_DEPLOYMENT_PROJECTNAME: Best Customer Corporate Website
  COMPOSER_CACHE_DIR: $CI_PROJECT_DIR/.cache/composer
  NPM_CACHE_DIR: $CI_PROJECT_DIR/.cache/npm
  YARN_CACHE_DIR: $CI_PROJECT_DIR/.cache/yarn
  GULP_PRODUCTION: 'true'
  GIT_DEPTH: 10

cache:
  key: "$CI_PROJECT_ID-$CI_COMMIT_REF_NAME"
  paths:
    - $CI_PROJECT_DIR/.cache/yarn
    - $CI_PROJECT_DIR/.cache/composer
    - $CI_PROJECT_DIR/.cache/npm


test:composer:
  stage: test
  image: composer:latest
  script:
    - echo "Validate app/composer.json:"
    - composer validate --working-dir=./app --no-check-all --strict
    - echo "Validate bin/dependencies/php/composer.json:"
    - composer validate --working-dir=./bin/dependencies/php --no-check-all --strict
