preset: psr2

enabled:
    - blank_line_after_opening_tag
    - concat_with_spaces
    - declare_strict_types
    - function_typehint_space
    - hash_to_slash_comment
    - lowercase_cast
    - native_function_casing
    - no_alias_functions
    - no_blank_lines_after_phpdoc
    - no_blank_lines_between_imports
    - no_empty_statement
    - no_extra_consecutive_blank_lines
    - no_leading_import_slash
    - no_leading_namespace_whitespace
    - no_short_bool_cast
    - no_singleline_whitespace_before_semicolons
    - no_trailing_comma_in_singleline_array
    - no_unneeded_control_parentheses
    - no_unused_imports
    - no_whitespace_before_comma_in_array
    - no_whitespace_in_blank_line
    - ordered_imports
    - phpdoc_no_package
    - phpdoc_scalar
    - self_accessor
    - short_array_syntax
    - single_blank_line_before_namespace
    - single_quote
    - whitespace_after_comma_in_array

finder:
  name:
    - "*.php"
  not-path:
    - ".Build"
    - "app/web/typo3conf/ext/theme/Resources/Private/Examples"
    - "app/Build/Scripts/T3xExtract.php"
