############################################################
### Load default processing options / Import other files ###
############################################################
imports:
    # Core's Processing.yaml contains the instructions for the code processing, when it is written to the database. The options are the same as in the RTE.default.proc. section of the pageTS config.
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    # Core's Base.yaml contains some basic settings like the width and height of the rte, buttons, which should be removed by default and so on.
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    # Core's Plugins.yaml registers custom plugins for ckeditor
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    # Additional plugins for ckeditor
    - { resource: "EXT:theme/Configuration/RTE/Additional/ExternalPlugins.yaml" }


######################################################################################
### Add configuration for the editor                                               ###
### For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config ###
######################################################################################
editor:
  config:

    # Custom stylesheets are provided with the option contentsCss. These styles are used in the RTE and should (must?) also be available in the frontend.
    contentsCss: ["EXT:rte_ckeditor/Resources/Public/Css/contents.css", "EXT:theme/Resources/Public/Css/rte.css" ]
#    contentsCss: ["EXT:rte_ckeditor/Resources/Public/Css/contents.css"]

    # Add disallowed content rules
    disallowedContent: "table[style,border]"

    stylesSet: []

    # Semicolon seperated list of items to be displayed in the Format drop-down list of block levelin the toolbar http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-format_tags
    format_tags: "p;h2;h3;h4"



    # List of classes to use for aligning the contents in the following order: left, center, right, justify http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-justifyClasses
    justifyClasses:
      - "text-left"
      - "text-center"
      - "text-right"
      - "text-justify"

    # Group all buttons http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-toolbarGroups
    toolbarGroups:
      - { name: styles, groups: [ styles, format ] }
      - { name: links, groups: [ links, anchor ] }
      - { name: basicstyles, groups: [ basicstyles ] }
#      - { name: paragraph, groups: [ list, indent, blocks, align ] }
      - { name: paragraph, groups: [ list ] }
      - { name: othertools, groups: [ deleteall ] }
      - "/"
      - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
      - { name: editing, groups: [ spellchecker ] }
      - { name: insert, groups: [ insert ] }
      - { name: tools, groups: [ quicktable, specialchar,insertcharacters, find ] }
      - { name: others}
      - { name: document, groups: [ mode ] }

    # toolbar is an alternative to toolbarGroups
#    toolbar:
#      - [ 'Link', 'Unlink', 'Anchor', 'Table', 'SpecialChar', 'CodeSnippet', 'Youtube' ]
#      - [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ]
#      - [ 'NumberedList', 'BulletedList']
#      - [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord' ]
#      - [ 'Undo', 'Redo', 'RemoveFormat', 'ShowBlocks' ]
#      - "/"
#      - [ 'Format', 'Styles' ]
#      - [ 'Bold', 'Italic', 'Underline', 'Blockquote', 'Subscript', 'Superscript']
#      - [ 'Source', 'Maximize', 'About', 'Find']

    # Additional plugins to be loaded
    extraPlugins:
      - justify
      - find
      - specialchar
      - showblocks
      - about
      - wordcount
      - selectall
#      - devtools

    # Plugins that must not be loaded
    removePlugins:
      - image
      - horizontalrule
#      - elementspath
#      - scayt

    # Toolbar button names that must not be rendered
    removeButtons:
#      - Anchor
      - Italic
      - Underline
#      - Superscript
#      - Subscript
#      - Table
      - Strike
#      - Styles

    # Clipboard/Pasting behaviour
    forcePasteAsPlainText: false
    clipboard_defaultContentType: "text"
    undoStackSize: 20
    pasteFromWordRemoveFontStyles: true

    # Editor sizing and misc settings
    width: "auto"
    height: 300
    resize_enabled: true
    resize_dir: "both"
    resize_maxWidth: "100%"
    resize_minWidth: 320
    resize_maxHeight: 1200
#    uiColor: "#F8F8F8"
    defaultLanguage: "de"
    defaultContentLanguage: "de"
    enableContextMenu: true
    browserContextMenuOnCtrl: true
    enterMode: 1
    shiftEnterMode: 2
#    startupMode: 'source'
    toolbarCanCollapse: true
    toolbarStartupExpanded: true
    toolbarLocation: "top"

    # Configure scayt spell check
    scayt_autoStartup: false
    # Configure default language https://docs.ckeditor.com/ckeditor4/latest/guide/dev_howtos_scayt.html#how-do-i-change-the-default-language-for-spell-check-as-you-type-scayt
    scayt_sLang: "de_DE"

    # Quicktable plugin configuration https://github.com/ufdada/quicktable/blob/master/plugin.js#L5
    qtClass: "table table-striped table-responsive table-bordered"

    # Configure wordcount plugin for ckeditor check details and all config options under https://github.com/w8tcha/CKEditor-wordcount-Plugin
    wordcount:
      showParagraphs: true
      showRemaining: false
      showWordCount: true
      showCharCount: true
      countSpacesAsChars: false
      countHTML: false
      countLineBreaks: false
      maxWordCount: -1
      maxCharCount: -1
      pasteWarningDuration: 3000


##################################
### Set the processing options ###
##################################
processing:
  # Tags that are allowed in the content (see also upstream sysext:rte_ckeditor/Configuration/RTE/Processing.yaml)
  allowTags:
    - s

  ## Tags that are allowed outside of paragraphs
#  allowTagsOutside: []

  ## allowed default attributes
  allowAttributes: [class, id, title, dir, lang, xml:lang, itemscope, itemtype, itemprop]

  ## CONTENT TO DATABASE
  HTMLparser_db:
    noAttrib: br
    tags:
      table:
        allowedAttribs:
          - class

# @TODO Check/Add CKEDITOR.config.copyFormatting_* features
# @TODO Check http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-find_highlight
# @TODO Check http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-format_address if it has to be used or only class in css is enough
# @TODO Check /Add CKEDITOR.config.format_(h1-h6|p|pre)
# @TODO Check/Add http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-indentClasses
# @TODO Develop a plugin based on the dialog plugin like the about plugin to display useful links for working with the RTE
